EnableMissingTranslationPlaceholders = "true"
baseurl = "/"
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-creative-theme"
title = "Hugo Creative Theme"
[params]
description = "Your description"
favicon = "favicon.ico"
name = "Your name"
[params.about]
buttontext = "Get started!"
description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
headline = "We've got what you need!"
[params.aside]
headline = "Get the Creative Theme for Hugo"
[params.aside.button]
link = "//github.com/digitalcraftsman/hugo-creative-theme"
text = "Download now"
[params.contact]
description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
email = "feedback@startbootstrap.com"
headline = "Let's Get In Touch!"
phone = "123-456-6789"
[params.hero]
buttontext = "Find out more"
slogan = "Your awesome slogan"
subtitle = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis nesciunt consequatur ut nihil voluptatem fugiat eos eveniet alias in veniam?"
[params.navigation]
brand = "Hugo Creative Theme"
[params.navigation.links]
about = "About"
contact = "Contact"
portfolio = "Portfolio"
services = "Services"
[params.portfolio.modal]
buttontext = "Close"
category = "Category"
client = "Client"
date = "Date"
[params.services]
headline = "At your service"
[[params.services.list]]
description = "Our templates are updated regularly so they don't break."
icon = "fa-diamond"
title = "Sturdy Templates"
[[params.services.list]]
description = "You can use this theme as is, or you can make changes!"
icon = "fa-paper-plane"
title = "Ready to Ship"
[[params.services.list]]
description = "We update dependencies to keep things fresh."
icon = "fa-newspaper-o"
title = "Up to Date"
[[params.services.list]]
description = "You have to make your websites with love these days!"
icon = "fa-heart"
title = "Made with Love"
